knp_paginator:
    page_range: 5                       # Количество ссылок на страницы в меню
    default_options:
        page_name: page                 # Имя параметра страницы в URL
        sort_field_name: sort           # Имя параметра сортировки
        sort_direction_name: direction  # Направление сортировки
        distinct: true                  # Исключать дубликаты
        filter_field_name: filterField
        filter_value_name: filterValue
    template:
        # ВОТ ЗДЕСЬ МЫ ЗАДАЕМ ДИЗАЙН BOOTSTRAP
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'